package exchange.persistence;

import exchange.domain.CurrencyPair;
import exchange.domain.Order;
import exchange.domain.Side;
import exchange.domain.Trade;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * Хранилище на встроенной СУБД H2 (файловый режим).
 * Все записи синхронизированы: одно соединение обслуживает все потоки биржи.
 */
public final class JdbcExchangeStore implements ExchangeStore {

    private final Connection connection;

    public JdbcExchangeStore(String jdbcUrl) {
        try {
            this.connection = DriverManager.getConnection(jdbcUrl, "sa", "");
            createSchema();
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    private void createSchema() throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS orders (
                        id BIGINT PRIMARY KEY,
                        client_id VARCHAR(255) NOT NULL,
                        base VARCHAR(16) NOT NULL,
                        quote VARCHAR(16) NOT NULL,
                        side VARCHAR(8) NOT NULL,
                        price VARCHAR(128) NOT NULL,
                        remaining VARCHAR(128) NOT NULL
                    )""");
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS trades (
                        id BIGINT PRIMARY KEY,
                        base VARCHAR(16) NOT NULL,
                        quote VARCHAR(16) NOT NULL,
                        price VARCHAR(128) NOT NULL,
                        amount VARCHAR(128) NOT NULL,
                        buyer_id VARCHAR(255) NOT NULL,
                        seller_id VARCHAR(255) NOT NULL
                    )""");
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS notifications (
                        seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        client_id VARCHAR(255) NOT NULL,
                        trade_id BIGINT NOT NULL
                    )""");
            statement.execute(
                    "CREATE INDEX IF NOT EXISTS idx_notifications_client ON notifications (client_id)");
        }
    }

    @Override
    public synchronized void begin() {
        try {
            connection.setAutoCommit(false);
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    @Override
    public synchronized void commit() {
        try {
            connection.commit();
            connection.setAutoCommit(true);
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    @Override
    public synchronized void rollback() {
        try {
            connection.rollback();
            connection.setAutoCommit(true);
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    @Override
    public synchronized void saveOrder(CurrencyPair pair, Order order) {
        // MERGE: новая заявка вставляется, существующая (исполнившаяся) обновляется.
        try (PreparedStatement statement = connection.prepareStatement(
                "MERGE INTO orders (id, client_id, base, quote, side, price, remaining) "
                        + "KEY (id) VALUES (?, ?, ?, ?, ?, ?, ?)")) {
            statement.setLong(1, order.id());
            statement.setString(2, order.clientId());
            statement.setString(3, pair.base());
            statement.setString(4, pair.quote());
            statement.setString(5, order.side().name());
            statement.setString(6, order.limitPrice().toPlainString());
            statement.setString(7, order.remainingAmount().toPlainString());
            statement.executeUpdate();
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    @Override
    public synchronized void saveTrade(Trade trade) {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO trades (id, base, quote, price, amount, buyer_id, seller_id) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?)")) {
            statement.setLong(1, trade.id());
            statement.setString(2, trade.pair().base());
            statement.setString(3, trade.pair().quote());
            statement.setString(4, trade.price().toPlainString());
            statement.setString(5, trade.amount().toPlainString());
            statement.setString(6, trade.buyerId());
            statement.setString(7, trade.sellerId());
            statement.executeUpdate();
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    @Override
    public synchronized void addNotification(String clientId, long tradeId) {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO notifications (client_id, trade_id) VALUES (?, ?)")) {
            statement.setString(1, clientId);
            statement.setLong(2, tradeId);
            statement.executeUpdate();
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    @Override
    public synchronized List<StoredOrder> loadWaitingOrders() {
        List<StoredOrder> result = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement(
                "SELECT id, client_id, base, quote, side, price, remaining FROM orders");
             ResultSet rows = statement.executeQuery()) {
            while (rows.next()) {
                Order order = new Order(
                        rows.getLong("id"),
                        rows.getString("client_id"),
                        Side.valueOf(rows.getString("side")),
                        new BigDecimal(rows.getString("price")),
                        new BigDecimal(rows.getString("remaining")));
                if (!order.isFilled()) {
                    result.add(new StoredOrder(
                            new CurrencyPair(rows.getString("base"), rows.getString("quote")),
                            order));
                }
            }
            return result;
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    @Override
    public synchronized long maxOrderId() {
        return maxId("orders");
    }

    @Override
    public synchronized long maxTradeId() {
        return maxId("trades");
    }

    private long maxId(String table) {
        try (PreparedStatement statement =
                     connection.prepareStatement("SELECT COALESCE(MAX(id), 0) FROM " + table);
             ResultSet rows = statement.executeQuery()) {
            rows.next();
            return rows.getLong(1);
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    @Override
    public synchronized List<Trade> loadNotifications(String clientId) {
        List<Trade> result = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement(
                "SELECT t.id, t.base, t.quote, t.price, t.amount, t.buyer_id, t.seller_id "
                        + "FROM notifications n JOIN trades t ON t.id = n.trade_id "
                        + "WHERE n.client_id = ? ORDER BY n.seq")) {
            statement.setString(1, clientId);
            try (ResultSet rows = statement.executeQuery()) {
                while (rows.next()) {
                    result.add(new Trade(
                            rows.getLong("id"),
                            new CurrencyPair(rows.getString("base"), rows.getString("quote")),
                            new BigDecimal(rows.getString("price")),
                            new BigDecimal(rows.getString("amount")),
                            rows.getString("buyer_id"),
                            rows.getString("seller_id")));
                }
            }
            return result;
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    @Override
    public synchronized void deleteNotifications(String clientId) {
        try (PreparedStatement statement = connection.prepareStatement(
                "DELETE FROM notifications WHERE client_id = ?")) {
            statement.setString(1, clientId);
            statement.executeUpdate();
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    @Override
    public synchronized void close() {
        try {
            connection.close();
        } catch (SQLException e) {
            throw failure(e);
        }
    }

    private static IllegalStateException failure(SQLException e) {
        return new IllegalStateException("Ошибка доступа к базе данных", e);
    }
}
